### PR TITLE
Dependencies with classifier show up as unused

### LINKED ISSUE #34: Classifier dependency shows up as unused
in build.sbt adding `"software.amazon.cryptools"   % "AmazonCorrettoCryptoProvider"    % "1.1.0" classifier "linux-x86_64"` to libraryDependencies and using in source code will show up as unused

Upon debugging the filename passed to BoringStuff.jarFileToDependency is `/Users/anilkumarmyla/.ivy2/cache/software.amazon.cryptools/AmazonCorrettoCryptoProvider/jars/AmazonCorrettoCryptoProvider-1.1.0-linux-x86_64.jar` and the logic tries to find the ivy directory for any of the possible versions out of which 1.1.0 is never a possible candidate (see below) failing to find `/Users/anilkumarmyla/.ivy2/cache/software.amazon.cryptools/AmazonCorrettoCryptoProvider/ivy-1.1.0.xml`

```
scala> import java.io.File
import java.io.File

scala> val a: File = new File("/Users/anilkumarmyla/.ivy2/cache/software.amazon.cryptools/AmazonCorrettoCryptoProvider/jars/AmazonCorrettoCryptoProvider-1.1.0-linux-x86_64.jar")
a: java.io.File = /Users/anilkumarmyla/.ivy2/cache/software.amazon.cryptools/AmazonCorrettoCryptoProvider/jars/AmazonCorrettoCryptoProvider-1.1.0-linux-x86_64.jar

scala> a.getName.dropRight(4).split('-').tails.filter(_.nonEmpty).toList.map(_.mkString("-")).reverse
res0: List[String] = List(x86_64, linux-x86_64, 1.1.0-linux-x86_64, AmazonCorrettoCryptoProvider-1.1.0-linux-x86_64)
```

### PR DESCRIPTION
**Pull request by anilkumarmyla**
Fixes #34 

Given artifact-hyphenatedVersion (parts 1-k), this one searches `1 + 2(k-1) => 2k -1` possible versions instead of k.
Ex: Given `abc-f-g-h-k`, searches `k, h-k, g-h-k, f-g-h-k, f-g-h, f-g, f` as possible versions while the previous one searched `k, h-k, g-h-k, f-g-h-k, abc-f-g-h-k`

### CODE REVIEW

**Comment by cb372** [comment]
Thanks! The change looks good.

Could you add a test case under `src/sbt-test/basic/` please? Hopefully the format of the sbt-scripted tests is reasonably clear. You could use the `AmazonCorrettoCryptoProvider` dependency from #34 for your test.

**Comment by anilkumarmyla** [comment]
@cb372 thanks for the review, I'll definitely add a test case. Upon deeper thoughts, an artifact with hyphen in its name (which most of them do) and a classifier would still show up as unused even with this fix ex: base-core-1.1.0-linux-x86_64. Then it becomes an even more exhaustive search. We can handle those ones later if anyone reports.

**Comment by anilkumarmyla** [comment]
@cb372 Added `no-unused-no-undeclared-classifier` test by simply copying `no-unused-no-undeclared-provided` test and making the changes. Over that flow discovered that scalaVersion is not the latest where I copied from and bumped to latest scalaVersion in both. Also verified that this test fails without the first commit 👍

**Comment by cb372** [comment]
Perfect, thanks!

**Comment by cb372** [comment]
Released as v0.2.10.

**Pull request merged**
